@echo off
echo Building PLU...
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:TRACE /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /debug:pdbonly /filealign:512 /optimize+ /out:plu\obj\x86\Release\Plu.exe /target:exe /win32manifest:plu\Properties\app.manifest plu\Program.cs plu\Properties\AssemblyInfo.cs
echo Copying Plu.exe..
copy /Y /B plu\obj\x86\Release\Plu.exe /B plu\bin\Release\Plu.exe
echo Core Res Gen...
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools\x64\Tracker.exe @"%temp%\6b2ec87094d943b2b63cb73828d890b6.tmp"  /c "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\ResGen.exe" /useSourcePath /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\Accessibility.dll /r:"%CD%\Lib\Microsoft.DirectX.AudioVideoPlayback.dll" /r:"%CD%\Lib\Microsoft.DirectX.dll" /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Windows.Forms.dll /compile About.resx,obj\x86\Release\PLRenewer.About.resources AutoCross.resx,obj\x86\Release\PLRenewer.AutoCross.resources MainForm.resx,obj\x86\Release\PLRenewer.MainForm.resources FormMDX.resx,obj\x86\Release\PLRenewer.FormMDX.resources M3uPreview.resx,obj\x86\Release\PLRenewer.M3uPreview.resources "My Project\Resources.resx",obj\x86\Release\PLRenewer.Resources.resources PLPW.resx,obj\x86\Release\PLRenewer.PLPW.resources Register.resx,obj\x86\Release\PLRenewer.Register.resources Updater.resx,obj\x86\Release\PLRenewer.Updater.resources 
echo Core Build...
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Vbc.exe /noconfig /imports:Microsoft.VisualBasic,System,System.Collections,System.Collections.Generic,System.Drawing,System.Diagnostics,System.Windows.Forms /optioncompare:Binary /optionexplicit+ /optionstrict+ /nowarn:42353,42354,42355 /optioninfer+ /nostdlib /platform:x86 /rootnamespace:PLRenewer /sdkpath:C:\Windows\Microsoft.NET\Framework\v2.0.50727 /define:"CONFIG=\"Release\",_MyType=\"WindowsFormsWithCustomSubMain\",PLATFORM=\"x86\"" /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\Accessibility.dll,"%CD%\Lib\Microsoft.DirectX.AudioVideoPlayback.dll","%CD%\Lib\Microsoft.DirectX.dll",C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll,C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll,C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Windows.Forms.dll /main:PLRenewer.Main /filealign:512 /out:obj\x86\Release\PLRenewer.exe /resource:obj\x86\Release\PLRenewer.About.resources /resource:obj\x86\Release\PLRenewer.AutoCross.resources /resource:obj\x86\Release\PLRenewer.MainForm.resources /resource:obj\x86\Release\PLRenewer.FormMDX.resources /resource:obj\x86\Release\PLRenewer.M3uPreview.resources /resource:obj\x86\Release\PLRenewer.Resources.resources /resource:obj\x86\Release\PLRenewer.PLPW.resources /resource:obj\x86\Release\PLRenewer.Register.resources /resource:obj\x86\Release\PLRenewer.Updater.resources /resource:plu\bin\Release\Plu.exe,PLRenewer.Plu.exe /target:winexe /win32icon:PLR.ico /win32manifest:"My Project\app.manifest" About.Designer.vb About.vb API.vb ApplicationEvents.vb AutoCross.Designer.vb AutoCross.vb GlassEnabledControls.vb MainForm.2.vb MainForm.vb MainForm.Designer.vb FormMDX.Designer.vb FormMDX.vb License.vb M3uPreview.Designer.vb M3uPreview.vb Main.vb "My Project\AssemblyInfo.vb" "My Project\Application.Designer.vb" "My Project\Resources.Designer.vb" "My Project\Settings.Designer.vb" Player.vb PLPW.Designer.vb PLPW.vb Register.Designer.vb Register.vb RegressBar.vb TagReader.vb TagWriter.vb TheLine.vb Updater.Designer.vb Updater.vb W7.vb /warnaserror+:41999,42016,42017,42018,42019,42020,42021,42022,42032,42036
echo Finished!